FROM ruby:<%= @ruby_version %>
LABEL maintainer="paul@error.agency"

# Install curl for fetching other apt repos
RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends apt-transport-https nano gpg

# Add NodeJS repo
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

# Add Yarn repo
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends nodejs yarn

RUN gem update --system && gem install bundler -v '2'

# Configure bundler and PATH
ENV LANG=C.UTF-8 \
GEM_HOME=/bundle \
BUNDLE_JOBS=4 \
BUNDLE_RETRY=3
ENV BUNDLE_PATH $GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH \
BUNDLE_BIN=$BUNDLE_PATH/bin
ENV PATH /app/bin:$BUNDLE_BIN:$PATH

RUN mkdir -p /app

ENTRYPOINT ["/app/config/docker/rails_base/entrypoint.sh"]
WORKDIR /app
